[default]
# This is the default value that is written into new pyproject.toml
# files for the `project.requires-python` key
requires-python = ">= 3.10"

# This is the default build system that is used
# build-system = "hatchling"

# This is the default license that is used
# license = "MIT"

# The dependency operator to use by default for dependencies.  The options are
# '>=', '~=', and '=='.  The default currently is '>='.  This affects the behavior
# of `rye add`.
dependency-operator = ">="

# [proxy]
# http = "http://127.0.0.1:4000"
# https = "http://127.0.0.1:4000"

[behavior]
# When set to true the `managed` flag is always assumed to be true.
force-rye-managed = false

# Enables global shims when set to `true`.  This means that the installed
# `python` shim will resolve to a Rye managed toolchain even outside of
# virtual environments.
global-python = false

# a array of tables with optional sources.  Same format as in pyproject.toml
# [[sources]]
# name = "default"
# url = "https://pypi.org/simple"
[[sources]]
name = "tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
