# vim:fileencoding=utf-8:foldmethod=marker

# : Manager {{{

[manager]
folder_offset = [2, 0, 2, 0]
preview_offset = [2, 1, 2, 1]

cwd = { fg = "#8bd5ca" }
# cwd = { fg = "#87afff" }

# Hovered
# hovered = { fg = "#24273a", bg = "#8aadf4" }
hovered = { fg = "#262626", bg = "#87afff" }
preview_hovered = { underline = false }

# Find
find_keyword = { fg = "#eed49f", italic = true }
find_position = { fg = "#f5bde6", bg = "reset", italic = true }

# Marker
marker_selected = { fg = "#a6da95", bg = "#a6da95" }
marker_copied = { fg = "#eed49f", bg = "#eed49f" }
marker_cut = { fg = "#ed8796", bg = "#ed8796" }

# Tab
tab_active = { fg = "#24273a", bg = "#8aadf4" }
tab_inactive = { fg = "#cad3f5", bg = "#494d64" }
tab_width = 1

# Border
border_symbol = "│"
border_style = { fg = "#8087a2" }

# Highlighting
syntect_theme = "~/.config/bat/themes/Catppuccin-macchiato.tmTheme"
# syntect_theme = "~/.config/bat/themes/TokyoNight.tmTheme"

# : }}}

# : Status {{{

[status]
# separator_open = ""
# separator_close = ""
# separator_style = { fg = "#494d64", bg = "#494d64" }
separator_open = ""
separator_close = ""
separator_style = { fg = "#4e4e4e", bg = "#4e4e4e" }

# Mode
mode_normal = { fg = "#24273a", bg = "#8aadf4", bold = true }
mode_select = { fg = "#24273a", bg = "#a6da95", bold = true }
mode_unset = { fg = "#24273a", bg = "#f0c6c6", bold = true }

# Progress
progress_label = { fg = "#ffffff", bold = true }
progress_normal = { fg = "#8aadf4", bg = "#494d64" }
progress_error = { fg = "#ed8796", bg = "#494d64" }

# Permissions
permissions_t = { fg = "#8aadf4" }
permissions_r = { fg = "#eed49f" }
permissions_w = { fg = "#ed8796" }
permissions_x = { fg = "#a6da95" }
permissions_s = { fg = "#8087a2" }

# : }}}

# : Input {{{

[input]
border = { fg = "#8aadf4" }
title = {}
value = {}
selected = { reversed = true }

# : }}}

# : Select {{{

[select]
border = { fg = "#8aadf4" }
active = { fg = "#f5bde6" }
inactive = {}

# : }}}

# : Tasks {{{

[tasks]
border = { fg = "#8aadf4" }
title = {}
hovered = { underline = true }

# : }}}

# : Which {{{

[which]
mask = { bg = "#363a4f" }
cand = { fg = "#8bd5ca" }
rest = { fg = "#939ab7" }
desc = { fg = "#f5bde6" }
separator = "  "
separator_style = { fg = "#5b6078" }

# : }}}

# : Help {{{

[help]
on = { fg = "#f5bde6" }
exec = { fg = "#8bd5ca" }
desc = { fg = "#939ab7" }
hovered = { bg = "#5b6078", bold = true }
footer = { fg = "#494d64", bg = "#cad3f5" }

# : }}}

# : File-specific styles {{{

[filetype]

rules = [
  # Images
  { mime = "image/*", fg = "#8bd5ca" },

  # Videos
  { mime = "video/*", fg = "#eed49f" },
  { mime = "audio/*", fg = "#eed49f" },

  # Archives
  { mime = "application/zip", fg = "#f5bde6" },
  { mime = "application/gzip", fg = "#f5bde6" },
  { mime = "application/x-tar", fg = "#f5bde6" },
  { mime = "application/x-bzip", fg = "#f5bde6" },
  { mime = "application/x-bzip2", fg = "#f5bde6" },
  { mime = "application/x-7z-compressed", fg = "#f5bde6" },
  { mime = "application/x-rar", fg = "#f5bde6" },

  # Fallback
  { name = "*", fg = "#cad3f5" },
  { name = "*/", fg = "#8aadf4" },
]

# : }}}

[icons]

"Desktop/"     = ""
"Documents/"   = ""
"Downloads/"   = ""
"Pictures/"    = ""
"Music/"       = ""
"Movies/"      = ""
"Videos/"      = ""
"Public/"      = ""
"Library/"     = ""
"Development/" = ""
".config/"     = ""

# Git
".git/"          = ""
".gitignore"     = ""
".gitmodules"    = ""
".gitattributes" = ""

# Dotfiles
".DS_Store"    = ""
".bashrc"      = ""
".bashprofile" = ""
".zshrc"       = ""
".zshenv"      = ""
".zprofile"    = ""
".vimrc"       = ""

# Text
"*.txt" = ""
"*.md"  = ""

# Archives
"*.zip" = ""
"*.tar" = ""
"*.gz"  = ""
"*.7z"  = ""

# Audio
"*.mp3"  = ""
"*.flac" = ""
"*.wav"  = ""

# Movies
"*.mp4" = ""
"*.mkv" = ""
"*.avi" = ""
"*.mov" = ""

# Images
"*.jpg"  = ""
"*.jpeg" = ""
"*.png"  = ""
"*.gif"  = ""
"*.webp" = ""
"*.avif" = ""
"*.bmp"  = ""
"*.ico"  = ""
"*.svg"  = ""

# Programming
"*.c"     = ""
"*.cpp"   = ""
"*.h"     = ""
"*.hpp"   = ""
"*.rs"    = ""
"*.go"    = ""
"*.py"    = ""
"*.js"    = ""
"*.ts"    = ""
"*.tsx"   = ""
"*.jsx"   = ""
"*.rb"    = ""
"*.php"   = ""
"*.java"  = ""
"*.sh"    = ""
"*.fish"  = ""
"*.swift" = ""
"*.vim"   = ""
"*.lua"   = ""
"*.html"  = ""
"*.css"   = ""
"*.scss"  = ""
"*.json"  = ""
"*.toml"  = ""
"*.yml"   = ""
"*.yaml"  = ""
"*.ini"   = ""
"*.conf"  = ""

# Default
"*"  = ""
"*/" = ""
