[manager]
layout = [1, 3, 4]
sort_by = "natural"
sort_reverse = false
sort_dir_first = true
show_hidden = false
show_symlink = false

[preview]
tab_size = 2
max_width = 26000
max_height = 29000
cache_dir = ""

[opener]
folder = [
  { exec = 'hyprctl dispatch exec "[float; size 60% 60%; center 1] xdg-open" "$@"', desc = "Open in GUI File Manager" },
  { exec = '$EDITOR "$@"' },
]
archive = [{ exec = 'xdg-open "$1"', desc = "Extract here" }]
pdf = [{ exec = 'zathura "$1"', desc = "Open" }]
docx = [{ exec = 'xdg-open "$1"', desc = "Open" }]
text = [
  # { exec = 'pypr hide yazi & kitty --detach $EDITOR "$@"', block = true, desc = "Open" },
  { exec = '$EDITOR "$@"', block = true, desc = "Open" },
]
image = [
  { exec = 'nsxiv "$@"', desc = "Open" },
  { exec = '''exiftool "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show EXIF" },
]
video = [
  { exec = 'mpv "$@"' },
  { exec = '''mediainfo "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show media info" },
]
audio = [
  { exec = 'mpv "$@"' },
  { exec = '''mediainfo "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show media info" },
]
fallback = [
  { exec = 'open "$@"', desc = "Open" },
  { exec = 'open -R "$@"', desc = "Reveal in Finder" },
]

[open]
rules = [
  { name = "*/", use = "folder" },

  { mime = "text/*", use = "text" },
  { mime = "text/docx", use = "docx" },
  { mime = "image/*", use = "image" },
  { mime = "video/*", use = "video" },
  { mime = "audio/*", use = "audio" },
  { mime = "inode/x-empty", use = "text" },

  { mime = "application/json", use = "text" },
  { mime = "*/javascript", use = "text" },

  { mime = "application/pdf", use = "pdf" },
  { mime = "application/zip", use = "archive" },
  { mime = "application/gzip", use = "archive" },
  { mime = "application/x-bzip", use = "archive" },
  { mime = "application/x-bzip2", use = "archive" },
  { mime = "application/x-tar", use = "archive" },
  { mime = "application/x-7z-compressed", use = "archive" },
  { mime = "application/x-rar", use = "archive" },

  { mime = "*", use = "fallback" },
]

[tasks]
micro_workers = 5
macro_workers = 10
bizarre_retry = 5

[log]
enabled = false

[plugins]
preload = ["~/.config/yazi/ui.lua", "~/.config/yazi/symlink.lua"]
