[manager]
layout = [1, 4, 3]
# sort_by = "natural"
sort_by = "modified"
sort_reverse = true
sort_dir_first = true
linemode = "size"
show_hidden = false
show_symlink = false

[preview]
tab_size = 2
max_width = 26000
max_height = 29000
cache_dir = ""
ueberzug_scale  = 1
ueberzug_offset = [ 0, 0, 0, 0 ]

[input]
# cd
cd_title = "Change directory:"
cd_origin = "top-center"
cd_offset = [0, 2, 50, 3]

# create
create_title = "Create:"
create_origin = "top-center"
create_offset = [0, 2, 50, 3]

# rename
rename_title = "Rename:"
rename_origin = "hovered"
rename_offset = [0, 1, 50, 3]

# trash
trash_title = "Move {n} selected file{s} to trash? (y/N)"
trash_origin = "top-center"
trash_offset = [0, 2, 50, 3]

# delete
delete_title = "Delete {n} selected file{s} permanently? (y/N)"
delete_origin = "top-center"
delete_offset = [0, 2, 50, 3]

# find
find_title = ["Find next:", "Find previous:"]
find_origin = "top-center"
find_offset = [0, 2, 50, 3]

# search
search_title = "Search:"
search_origin = "top-center"
search_offset = [0, 2, 50, 3]

# shell
shell_title = ["Shell:", "Shell (block):"]
shell_origin = "top-center"
shell_offset = [0, 2, 50, 3]

# overwrite
overwrite_title = "Overwrite an existing file? (y/N)"
overwrite_origin = "top-center"
overwrite_offset = [0, 2, 50, 3]

# quit
quit_title = "{n} task{s} running, sure to quit? (y/N)"
quit_origin = "top-center"
quit_offset = [0, 2, 50, 3]

[select]
open_title = "Open with:"
open_origin = "hovered"
open_offset = [0, 1, 50, 7]

[opener] # sets of definitions of openers referenced in rules below
edit = [
{ run = 'nvim "$@"', desc = "nvim", block = true },
{ run = 'vim "$@"', desc = "vim", block = true },
{ run = 'nsxiv "$@"', desc = "nsxiv", block = true },
{ run = 'gvim "$@"', desc = "Gvim", block = true },
{ run = 'hyprctl "$@"', desc = "Hyprctl", block = true },
{ run = 'geany "$@"', desc = "Geany", block = true },
{ run = 'meld "$@"', desc = "meld", block = true },
{ run = 'libreoffice "$@"', desc = "LibreOffice", block = true },
{ run = 'zathura "$@"', desc = "Zathura", block = true },
]

open = [
{ run = 'xdg-open "$@"', desc = "Open" },
]

reveal = [
{ run = 'xdg-open "$(dirname "$0")"', desc = "Open dir in nemo" },
{ run = '''exiftool "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show EXIF" },
]

extract = [
{ run = 'unar "$1"', desc = "Extract to new folder" },
{ run = 'file-roller "$1"', desc = "Archive Manager" },
{ run = 'peazip "$1"', desc = "Peazip" },
]

play = [
{ run = 'celluloid "$@"', desc = "Celluloid", orphan = false },
{ run = 'audacity "$@"', desc = "Audacity", orphan = false },
{ run = '''mediainfo "$1"; echo "Press enter to exit"; read _''', block = true, desc = "Show media info" },
]

mp4edit = [
{ run = 'audacity "$@"', desc = 'Audacity', orphan = false },
{ run = 'celluloid "$@"', desc = 'Celluloid', orphan = false },
{ run = 'mpv "$@"', desc = 'Mpv', orphan = false },
]

aup3edit = [
{ run = 'audacity "$@"', desc = "Audacity", orphan = false },
]

imgedit = [
{ run = 'nsxiv "$@"', desc = "nsxiv", orphan = false },
{ run = 'feh "$@"', desc = "feh", orphan = false },
]

pdfedit = [
{ run = 'zathura "$@"', desc = "Zathura", orphan = false },
{ run = 'okular "$@"', desc = "Okular", orphan = false },
{ run = 'evince "$@"', desc = "Evince", orphan = false },
{ run = 'pdfarranger "$@"', desc = "PDF Arranger", orphan = false },
]

mdedit = [
{ run = 'nvim "$@"', desc = "nvim", block = true },
{ run = 'typora "$@"', desc = "typora", block = true },
{ run = 'geany "$@"', desc = "geany", block = true },
{ run = 'gvim "$@"', desc = "gvim", block = true },
{ run = 'vim "$@"', desc = "vim", block = true },
{ run = 'meld "$@"', desc = "meld", block = true },
]

[open] #rules for which opener(s) for which filetypes
rules = [
  { name = "*/", use = "folder" },
  { name = ".mp4", use = [ "mp4edit", "reveal" ] },
  { name = ".m4a", use = [ "mp4edit", "reveal" ] },
  { name = ".conf", use = [ "edit", "reveal" ] },
  { name = ".pdf", use = [ "pdfedit", "reveal" ] },
  { name = ".md", use = [ "mdedit", "reveal" ] },
  { name = "*.aup3", use = [ "aup3edit", "reveal" ] },

  { mime = "text/*",  use =          [ "edit", "reveal" ] },
  { mime = "text/docx", use = "docx" },
  { mime = "image/*", use = ["imgedit", "reveal"] },
  { mime = "video/*", use = "video" },
  { mime = "audio/*", use = "audio" },
  { mime = "inode/x-empty", use = "text" },

  { mime = "text/xlsx", use = "xlsx" },
  { mime = "application/pdf",             use = [ "pdfedit" ] },

  { mime = "*/javascript",     use = [ "edit", "reveal" ] },
  { mime = "application/json", use = [ "edit", "reveal" ] },

  { mime = "application/zip",             use = [ "extract" ] },
  { mime = "application/gzip",            use = [ "extract" ] },
  { mime = "application/x-tar",           use = [ "extract" ] },
  { mime = "application/x-bzip",          use = [ "extract" ] },
  { mime = "application/x-bzip2",         use = [ "extract" ] },
  { mime = "application/x-7z-compressed", use = [ "extract" ] },
  { mime = "application/x-rar",           use = [ "extract" ] },
  { mime = "application/xz",              use = [ "extract" ] },

  { mime = "*", use = [ "open", "reveal" ] },
]

[tasks]
micro_workers = 10
macro_workers = 25
bizarre_retry = 5
image_alloc = 536870912 # 512MB
image_bound = [0, 0]
suppress_preload = false

[plugin]
prepend_previewers = [
{ name = "txt", run = "code" },
{ name = ".md", run = "glow" },
{ name = ".od", run = "odt" },
{ name = ".wps", run = "odt" },
{ name = ".xlsx", run = "xlsx" },
{ name = ".xls", run = "xls" },
{ name = ".docx", run = "docx" },
{ name = ".doc", run = "doc" },
{ mime = "text/csv", run = "csv"},
{ mime = "audio/", run = "exifaudio" },
{ mime = "application/*zip", run = "ouch" },
{ mime = "application/x-tar", run = "ouch" },
{ mime = "application/x-bzip2", run = "ouch" },
{ mime = "application/x-7z-compressed", run = "ouch" },
{ mime = "application/x-rar", run = "ouch" },
{ mime = "application/xz", run = "ouch" },
]

[log]
enabled = false

[plugins]
preload = ["~/.config/yazi/ui.lua", "~/.config/yazi/symlink.lua"]
# preload = ["~/.config/yazi/hide_statusbar.lua"]
